language: objective-c
osx_image: xcode8.3
before_install:
    - brew update
    - brew install xctool --HEAD

xcode_workspace: JSONModelKit.xcworkspace
script:
    - xctool -workspace JSONModelKit.xcworkspace -scheme PLIST-iOSTests -sdk iphonesimulator10.3 run-tests
    - xctool -workspace JSONModelKit.xcworkspace -scheme JSON-iOSTests -sdk iphonesimulator10.3 run-tests
