language: objective-c
osx_image: xcode8.3
before_install:
    - brew update
    - brew install xctool

xcode_sdk:
- iphonesimulator10.3

xcode_workspace: JSONModelKit.xcworkspace
script:
    - xcodebuild -workspace JSONModelKit.xcworkspace -scheme JSON-iOSTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' test
